Update pipeline.yml

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -53,22 +53,17 @@ stages:
     PORT: 9080,22,80,443
     CONTAINER_NAME: rd-docker-liberty
     DEPLOY_TYPE: red_black
-    COMMAND: |-
-      #!/bin/bash
-      echo -e "${label_color}Starting deployment script${no_color}"
-
-      # get the required scripts
-      git_retry clone https://www.github.com/ralfduerig/docker-scripts.git deployscripts
-
-      # Deploy with containers
-      /bin/bash deployscripts/deploycontainer.sh
-
-      RESULT=$?
-
-      # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.
-      if [ $RESULT -ne 0 ]; then
-          echo -e "${red}Executed failed or had warnings ${no_color}"
-          ${EXT_DIR}/print_help.sh
-          exit $RESULT
-      fi
-      echo -e "${green}Execution complete${no_label}"
+    COMMAND:"#!/bin/bash \n\
+      \echo -e "${label_color}Starting deployment script${no_color}" \n\
+      \# get the required scripts \n\
+      \git_retry clone https://www.github.com/ralfduerig/docker-scripts.git deployscripts \n\
+      \# Deploy with containers \n\
+      \/bin/bash deployscripts/deploycontainer.sh \n\
+      \RESULT=$?  \n\
+      \# The following colors have been defined to help with presentation of logs: green, red, label_color, no_color. \
+      \if [ $RESULT -ne 0 ]; then \
+      \   echo -e "${red}Executed failed or had warnings ${no_color}" \
+      \  ${EXT_DIR}/print_help.sh \
+      \    exit $RESULT \n\
+      \fi \n\
+      \echo -e "${green}Execution complete${no_label}"
